# Generated by Django 4.2.4 on 2023-08-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('province', models.CharField(blank=True, choices=[('Gandaki Province', 'Gandaki Province'), ('Province No. 1', 'Province No. 1'), ('Madhesh Province', 'Madhesh Province'), ('Bagmati Province', 'Bagmati Province'), ('Lumbini Province', 'Lumbini Province'), ('Karnali Province', 'Karnali Province'), ('Sudurpaschim Province', 'Sudurpashcim Province')], max_length=30, verbose_name='Province')),
                ('district', models.CharField(blank=True, max_length=40, verbose_name='District')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='City')),
                ('tole', models.CharField(blank=True, max_length=80, verbose_name='Tole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('grade', models.CharField(blank=True, choices=[('A', ' A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=20, verbose_name='Grade')),
                ('major', models.CharField(blank=True, max_length=200, verbose_name='Majour')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='api.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
